#!/bin/sh

# WiFi 2.4 GHz
uci set wireless.radio0.disabled='0'
uci set wireless.radio0.country='IN'
uci set wireless.radio0.channel='auto'
uci set wireless.radio0.disassoc_low_ack='0'
uci set wireless.default_radio0.ssid='ApunkaWIFI'
uci set wireless.default_radio0.encryption='psk2'
uci set wireless.default_radio0.key='APEXPRIT'
uci set wireless.default_radio0.ieee80211r='1'
uci set wireless.default_radio0.ft_over_ds='1'
uci set wireless.default_radio0.ft_psk_generate_local='1'

# WiFi 5 GHz
uci set wireless.radio1.disabled='0'
uci set wireless.radio1.country='IN'
uci set wireless.radio1.channel='auto'
uci set wireless.radio1.disassoc_low_ack='0'
uci set wireless.default_radio1.ssid='ApunkaWIFI_5G'
uci set wireless.default_radio1.encryption='psk2'
uci set wireless.default_radio1.key='APEXPRIT'
uci set wireless.default_radio1.ieee80211r='1'
uci set wireless.default_radio1.ft_over_ds='1'
uci set wireless.default_radio1.ft_psk_generate_local='1'

uci commit wireless

# WAN static
uci set network.wan.proto='static'
uci set network.wan.ipaddr='10.21.152.215'
uci set network.wan.netmask='255.255.255.192'
uci set network.wan.gateway='10.21.152.193'
uci set network.wan.dns='1.1.1.1 8.8.8.8 103.211.23.130'
uci set network.wan.macaddr='5C:02:14:62:10:41'
uci set network.globals.packet_steering='1'
uci commit network

# Admin password
echo -e 'apexprit\napexprit' | passwd root

# DNS
uci set dhcp.@dnsmasq[0].server='1.1.1.1' '8.8.8.8' '103.211.23.130'
uci commit dhcp

exit 0

